### PR TITLE
fix rest_framework auth class

### PR DESCRIPTION
**Pull request by gawel**
I've tried to combine feedback from https://github.com/django-webtest/django-webtest/pull/92 , https://github.com/django-webtest/django-webtest/pull/100 and https://github.com/django-webtest/django-webtest/issues/98

Thoughts ? @hugorodgerbrown @merwok @Tenzer

### CODE REVIEW

**Comment by Tenzer** [comment]
Looks fine to me on first glance, but I haven't exercised the code in any way.

**Comment by bdauvergne** [comment]
For the problem I reported in #98, merwork indicated it could be simpler than a rename with `from __future__ import absolute_imports`. I'll let the local BDFL(s) say what they prefer.

**Comment by gawel** [comment]
@bdauvergne renaming is not that hard (and sorry I forgot to poke you)

**Comment by bdauvergne** [comment]
> @bdauvergne renaming is not that hard (and sorry I forgot to poke you)

Not my war :) Faster it's fixed, faster i'm happy.

**Comment by gawel** [comment]
Feel free to test with a `pip install -e git+git@github.com:django-webtest/django-webtest.git@fix_rest_auth_class`


I have no use case myself. That's why I'm requesting feedbacks.

I'll merge/release this ASAP after a few more feedback.

**Comment by bdauvergne** [comment]
I have tested your branch and it fixes the problem on our side (there http://git.entrouvert.org/welco.git).

**Comment by gawel** [comment]
Lets make a release

**Pull request merged**
