### PR TITLE
Allow 'click' to be given a user param

### PR DESCRIPTION
**Pull request by helenst**
This allows authentication to be continued when simulating link clicks

* Create utils module to contain update_environ function
* Override response click method to call update_environ

### CODE REVIEW

**Comment by gawel** [comment]
Are you sure that this is needed ? The app is supposed to store the auth cookie. Do you have one ?

**Comment by helenst** [comment]
This was a few months ago and I don't remember too well but I was trying to make my webtests more pytest-like, i.e. not with testcases - I had the auth working perfectly with a TestCase, but I think I was having to pass `user` to everything to get it working without. I ended up stashing and mostly forgetting the whole lot, and the whole idea may have been more trouble than it's worth. I'll close... :-)

**Comment by gawel** [comment]
Don't go too fast :)
I'll check

**Comment by gawel** [comment]
if you want the user to stay logged you can use app.extra_environ['WEBTEST_USER'] = username.
maybe this require a clever api.

**Comment by helenst** [comment]
Yeah, that's what I was doing in this PR (albeit wrapped in the same `update_environ` method already used by get, post etc. :-)

**Comment by RobinRamael** [comment]
Could this be included in a release?

**Comment by gawel** [comment]
I'm on it

**Comment by gawel** [comment]
https://pypi.python.org/pypi/django-webtest

**Comment by RobinRamael** [comment]
thanks!

**Comment by carn1x** [comment]
https://github.com/django-webtest/django-webtest/blob/master/CHANGES.txt mentions "- Allow 'click' to be given a user param" however this was never merged?

**Pull request closed without merging**
