### PR TITLE
Update obtaining current session

### PR DESCRIPTION
**Pull request by shea-maykinmedia**
Fixes https://github.com/django-webtest/django-webtest/issues/113

Please see discussion in issue for context.

### CODE REVIEW

**Comment by gawel** [comment]
Can you add en entry to the change log ?

**Comment by shea-maykinmedia** [comment]
Sure!  Do you mean adding another bullet point under `1.9.8 (unreleased)` in the CHANGES.rst file?

**Comment by gawel** [comment]
yes :) thanks

**Comment by shea-maykinmedia** [comment]
Cool! It's added now :)

**Pull request merged**
