### PR TITLE
Allow get(user=None) to reset user from previous set_user call

### LINKED ISSUE #75: Calling a get/put/etc method with user=None is not equivalent to set_user=None
Hello!  I found a small inconsistency that’s mildly inconvenient.

Context: In a project where 90% of the views require authentication, I define a simple `app` fixture that calls `django_app.set_user('bill@example.ca')` and returns that testapp object.  For tests that check that the open views are indeed open, or that a specific view is indeed restricted (which is needed to make sure custom permissions work as intended with rest-framework for example), I can either use the base `django_app` fixture, or use my `app` and start the test with `app.set_user(None)` to remove `WEBTEST_USER` from the WSGI environment.

I found myself changing some tests to use a consistent style (pass `user=user2` or `user=None` everywhere instead of calling set_user in a few cases), and that did not reset the user.

Proposed fix: in `_update_environ`, use a sentinel object instead of None to determine if the `user` parameter was given or not; if it is None, remove `WEBTEST_USER`.

### PR DESCRIPTION
**Pull request by merwok**
Fixes #75

### CODE REVIEW

**Comment by merwok** [comment]
Travis CI seems to be unplugged here 😿

**Comment by gawel** [comment]
Looks like the last build is 4 monthes old... https://travis-ci.org/django-webtest/django-webtest/builds

**Comment by gawel** [comment]
And the latest commit is 4 monthes old :D Don't know why this PR didn't trigger anything. Travis is configured to check PR too...

**Comment by gawel** [comment]
And the merge triggered a build... https://travis-ci.org/django-webtest/django-webtest/builds/313577036

**Comment by merwok** [comment]
It looks like my addition of `request.user` doesn’t work with older djangos, probably a missing middleware class.

**Comment by merwok** [comment]
Fixed with PR #77

**Pull request merged**
